name: BDD 功能需求
description: 用於提交基於用戶行為的功能需求
labels: ["type: feature", "domain: bdd"]
assignees: []
title: "BDD: [功能名稱]"
body:
  - type: markdown
    attributes:
      value: |
        ## BDD 功能需求表單
        請填寫以下資訊，幫助開發團隊理解並實現你的功能需求
  
  - type: input
    id: feature-id
    attributes:
      label: 功能 ID
      description: 請輸入唯一的功能 ID (例如：REQ-001)
      placeholder: "REQ-001"
    validations:
      required: true

  - type: textarea
    id: user-story-and-scenarios
    attributes:
      label: User Story 與行為測試
      description: |
        請描述一個或多個 User Story（使用「作為...，我想要...，以便...」的格式），每個 User Story 後面接著對應的 Gherkin 語法（Given, When, Then）行為場景。可以有多個 User Story 和場景。
      placeholder: |
        **User Story 1：**
        作為[角色]，我想要[行為]，以便[好處]。

        **行為測試場景 1：**
        Feature: 註冊帳戶

        Scenario: 成功註冊
          Given 我在註冊頁面
          When 我輸入有效的電子郵件和密碼，並點擊「註冊」
          Then 我應該看到「註冊成功」訊息

        **User Story 2：**
        作為[角色]，我想要[行為]，以便[好處]。

        **行為測試場景 2：**
        Feature: 登入系統

        Scenario: 成功登入
          Given 我在登入頁面
          When 我輸入正確的帳號和密碼，並點擊「登入」
          Then 我應該進入主頁面
      render: gherkin
    validations:
      required: true

  - type: textarea
    id: related-issues
    attributes:
      label: 相關 SDD 與 TDD Issue
      description: |
        請列出每個 User Story 對應的 SDD（規範要求）和 TDD（測試驅動）Issue 編號。
        格式：User Story 1 -> SDD: #123, TDD: #456
      placeholder: |
        User Story 1 -> SDD: #123, TDD: #456
        User Story 2 -> SDD: #789, TDD: #101
