name: SDD 規範要求
description: 用於提交與規範、標準、合規性有關的要求。
labels: ["type: compliance", "domain: sdd"]
assignees: []
title: "S-[功能ID]-US[序號] - [設計領域]"
body:
  - type: markdown
    attributes:
      value: |
        ## SDD 規範要求表單
        請填寫以下資訊，幫助開發團隊確保系統符合相關規範與標準。

  - type: input
    id: standard
    attributes:
      label: 規範或標準名稱
      description: |
        請說明是哪一種規範或標準（例如：GDPR、PCI-DSS、WCAG 2.1、ISO 27001）
      placeholder: "GDPR"
    validations:
      required: true

  - type: textarea
    id: requirement-description
    attributes:
      label: 要求描述
      description: |
        請詳細描述此規範的具體要求。
        必須涵蓋本 SDD 對應的各個 BDD Scenario（見「對應 BDD Scenario」欄位），說明每個 Scenario 的具體設計規格。
        如涉及錯誤處理的情況，請使用 table 格式清晰呈現。
      placeholder: |
        ### 核心流程
        
        **US2-S1：BDD 已核准時的 SDD 問答流程**
        - 使用者在 Copilot Chat 中呼叫 `sdd.prompt.md`
        - AI Agent 檢查對應 BDD Issue 是否被加上 `approved` label
        - 若已核准，透過多輪問答蒐集系統設計資訊...
        
        ### 錯誤處理
        
        | 場景 | 處理方式 |
        | --- | --- |
        | 完整性判定失敗 | 若對話中欄位缺漏，系統提示使用者「請說明 [缺漏項目]」，不呼叫 GitHub API |
        | API 403（權限不足） | 回傳完整 Markdown 草稿供手動建立 |
        | API 429（速率限制） | 提示「已達 API 限制，請稍後重試」 |
        | API 5xx（伺服器錯誤） | 提示「GitHub 暫時故障，請稍後重試」並記錄 |
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: 受影響的元件或功能
      description: |
        請列出此規範要求會影響到的元件或功能。
        範例：使用者註冊、資料儲存、登入
      placeholder: |
        - 使用者註冊
        - 會員資料儲存

  - type: textarea
    id: verification-method
    attributes:
      label: 驗證方式
      description: |
        請說明如何驗證此規範是否已實現。
        可以是手動檢查、自動化測試、第三方驗證等。
      placeholder: |
        - 自動化測試檢查資料庫中密碼是否已加密
        - 使用工具驗證網站是否符合 WCAG 2.1

  - type: textarea
    id: bdd-scenarios
    attributes:
      label: 對應 BDD Scenario
      description: |
        列出本 SDD 涵蓋的 BDD Scenario ID 與行為摘要（每個 SDD Issue 必須涵蓋至少一個 BDD Scenario）。
        ID 必須沿用 BDD Issue 的 `US<序號>-S<序號>` 命名格式。
        「要求描述」應逐一說明各 Scenario 的具體設計規格。
      placeholder: |
        | BDD Scenario ID | 行為摘要 | 備註 |
        | --- | --- | --- |
        | US2-S1 | 開發人員呼叫 SDD Prompt 進行問答並建立 SDD Issue | 已確認 |
        | US2-S2 | BDD 未核准時拒絕進行 SDD 問答 | 已確認 |
      render: markdown
    validations:
      required: true
