name: SDD 規範要求
description: 用於提交與規範、標準、合規性有關的要求。
labels: ["type: compliance", "domain: sdd"]
assignees: []
title: "SDD: [領域] - [設計主題]"
body:
  - type: markdown
    attributes:
      value: |
        ## SDD 規範要求表單
        請填寫以下資訊，幫助開發團隊確保系統符合相關規範與標準。
        > SDD 必須衍生自單一 BDD Issue，並回填對應的 BDD Scenario ID。
  - type: input
    id: bdd-issue
    attributes:
      label: 對應 BDD Issue
      description: 請輸入此 SDD 依據的 BDD Issue 編號（格式為 `#123`）。
      placeholder: "#123"
    validations:
      required: true

  - type: input
    id: standard
    attributes:
      label: 規範或標準名稱
      description: |
        請說明是哪一種規範或標準（例如：GDPR、PCI-DSS、WCAG 2.1、ISO 27001）
      placeholder: "GDPR"
    validations:
      required: true

  - type: textarea
    id: requirement-description
    attributes:
      label: 要求描述
      description: |
        請詳細描述此規範的具體要求。
        必須涵蓋本 SDD 對應的各個 BDD Scenario（見「對應 BDD Scenario」欄位），說明每個 Scenario 的具體設計規格。
      placeholder: |
        使用者上傳的個人資料必須加密儲存，並在 7 天後自動刪除。
        
        對應 Scenario：
        - US2-S1：當 BDD Issue 已批准時，系統應自動檢查批准狀態，若通過則進入 SDD 問答流程...
        - US2-S2：當 BDD Issue 未批准時，系統應拒絕進行 SDD 問答並提示相應訊息...
    validations:
      required: true

  - type: textarea
    id: affected-components
    attributes:
      label: 受影響的元件或功能
      description: |
        請列出此規範要求會影響到的元件或功能。
        範例：使用者註冊、資料儲存、登入
      placeholder: |
        - 使用者註冊
        - 會員資料儲存

  - type: textarea
    id: verification-method
    attributes:
      label: 驗證方式
      description: |
        請說明如何驗證此規範是否已實現。
        可以是手動檢查、自動化測試、第三方驗證等。
      placeholder: |
        - 自動化測試檢查資料庫中密碼是否已加密
        - 使用工具驗證網站是否符合 WCAG 2.1

  - type: textarea
    id: bdd-scenarios
    attributes:
      label: 對應 BDD Scenario
      description: |
        列出本 SDD 涵蓋的 BDD Scenario ID 與行為摘要（每個 SDD Issue 必須涵蓋至少一個 BDD Scenario）。
        ID 必須沿用 BDD Issue 的 `US<序號>-S<序號>` 命名格式。
        「要求描述」應逐一說明各 Scenario 的具體設計規格。
      placeholder: |
        | BDD Scenario ID | 行為摘要 | 備註 |
        | --- | --- | --- |
        | US2-S1 | 開發人員呼叫 SDD Prompt 進行問答並建立 SDD Issue | 已確認 |
        | US2-S2 | BDD 未批准時拒絕進行 SDD 問答 | 已確認 |
      render: markdown
    validations:
      required: true

  - type: textarea
    id: related-tdd
    attributes:
      label: 相關 TDD Issue
      description: |
        列出基於此 SDD 設計而產生的 TDD Issue 編號（例如：#3, #4, #5）。TDD Issue 會參考此 SDD 的設計規範進行測試。
      placeholder: "#3, #4, #5"

  - type: textarea
    id: reference-sdd
    attributes:
      label: 參考的舊 SDD Issue
      description: |
        若此 SDD 參考過去的設計決策或規範，請列出舊 SDD Issue 編號並標注「參考自」（例如：參考自 #2, #5）。用於追蹤設計演進歷史。
      placeholder: "參考自 #2, #5"

  - type: textarea
    id: other-related-issues
    attributes:
      label: 其他相關 Issue 或任務
      description: |
        若此 SDD 與其他 Issue（如技術債、Bug、文件）有關，請列出編號。
      placeholder: "#456, #789"
