name: TDD 測試驅動
description: 用於提交基於測試驅動開發的測試需求。
labels: ["type: test", "domain: tdd"]
assignees: []
title: "TDD: [測試名稱]"
body:
  - type: markdown
    attributes:
      value: |
        ## TDD 測試驅動表單
        請填寫以下資訊，幫助開發團隊先寫測試，再去寫程式碼

  - type: input
    id: bdd-issue
    attributes:
      label: 對應 BDD Issue
      description: 請輸入此 TDD 對應的 BDD Issue 編號（格式為 #123）。
      placeholder: "#123"
    validations:
      required: true

  - type: textarea
    id: test-scenarios
    attributes:
      label: 測試場景
      description: |
        請列出多組測試場景，每組包括場景名稱、輸入條件、預期行為和邊界條件。使用 checkbox 語法 (- [ ]) 來標記每個場景，實現完成後打勾。
      placeholder: |
        - [ ] **場景 1: 成功註冊**
          - 輸入: 有效的電子郵件和密碼
          - 預期: 顯示「註冊成功」訊息
          - 邊界條件: 密碼至少 8 字符

        - [ ] **場景 2: 密碼太短**
          - 輸入: 有效的電子郵件，密碼少於 8 字符
          - 預期: 顯示錯誤訊息「密碼太短」
          - 邊界條件: 密碼長度檢查

        - [ ] **場景 3: 無效電子郵件**
          - 輸入: 無效格式的電子郵件
          - 預期: 顯示錯誤訊息「電子郵件格式錯誤」
          - 邊界條件: 電子郵件驗證規則

  - type: textarea
    id: test-data
    attributes:
      label: 測試資料
      description: |
        請說明此 TDD 所需的測試資料策略，包括資料來源、Mock vs 真實資料、資料準備方式等。
      placeholder: |
        - Mock 資料來源: 使用 Jest 的 Mock fixtures
        - 真實資料: 需要測試資料庫的測試環境
        - 資料準備: 使用 setup.js 進行初始化
        - 邊界資料: 空值、超大值、特殊字元等

  - type: textarea
    id: expected-results
    attributes:
      label: 預期結果與通過條件
      description: |
        請列出每個測試場景的預期結果和通過條件，用 checkbox 語法標記實現進度。
      placeholder: |
        - [ ] 場景 1 通過條件：返回 HTTP 201 + 包含 user_id 的 JSON 回應
        - [ ] 場景 2 通過條件：返回 HTTP 400 + 錯誤訊息「密碼長度至少 8 字符」
        - [ ] 場景 3 通過條件：返回 HTTP 400 + 錯誤訊息「無效的電子郵件格式」
        - [ ] 所有場景覆蓋率達 90% 以上


