name: TDD 測試驅動
description: 用於提交基於測試驅動開發的測試需求。
labels: ["type: test", "domain: tdd"]
assignees: []
title: "TDD: [測試名稱]"
body:
  - type: markdown
    attributes:
      value: |
        ## TDD 測試驅動表單
        請填寫以下資訊，幫助開發團隊先寫測試，再去寫程式碼

  - type: textarea
    id: test-scenarios
    attributes:
      label: 測試場景
      description: |
        請列出多組測試場景，每組包括場景名稱、輸入條件、預期行為和邊界條件。使用 checkbox 語法 (- [ ]) 來標記每個場景，實現完成後打勾。
      placeholder: |
        - [ ] **場景 1: 成功註冊**
          - 輸入: 有效的電子郵件和密碼
          - 預期: 顯示「註冊成功」訊息
          - 邊界條件: 密碼至少 8 字符

        - [ ] **場景 2: 密碼太短**
          - 輸入: 有效的電子郵件，密碼少於 8 字符
          - 預期: 顯示錯誤訊息「密碼太短」
          - 邊界條件: 密碼長度檢查

        - [ ] **場景 3: 無效電子郵件**
          - 輸入: 無效格式的電子郵件
          - 預期: 顯示錯誤訊息「電子郵件格式錯誤」
          - 邊界條件: 電子郵件驗證規則
